window:
  padding:
    x: 10
    y: 10

  dynamic_padding: false
  dynamic_title: true

font:
  size: 12
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    style: Bold
  italic:
    style: Italic
  bold_italic:
    style: Bold Italic
  
live_config_reload: true

key_bindings:
  - { key: V, mode: Vi, action: ToggleNormalSelection }

